# Generated by Django 4.0 on 2022-01-08 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_date_of_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_of_post',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 1, 8, 22, 7, 30, 255581)),
        ),
    ]
